---
- name: Get-WinUserLanguageList
  win_shell: |
    $test = (Get-WinUserLanguageList)[0].LanguageTag
    Write-Host $test
  register: language_tag
  changed_when: False

- debug:
    var: language_tag.stdout

- name: Set-WinUserLanguageList
  win_shell: |
    Set-WinUserLanguageList -Languagelist '{{ win_user_language }}' -Force
  when: language_tag.stdout is not match(win_user_language)